

 -- DROP TABLES: 
 DROP TABLE IF EXISTS ERS_REIMBURSEMENT_STATUS;
 DROP TABLE IF EXISTS ERS_REIMBURSEMENT_TYPE;
 DROP TABLE IF EXISTS ERS_USER_ROLES;
 DROP TABLE IF EXISTS ERS_USERS;
 DROP TABLE IF EXISTS ERS_REIMBURSEMENT;
 
 -- SELECT * FROM TABLES:
 SELECT * FROM ers_reimbursement_status; 
 SELECT * FROM ers_reimbursement_type;
 SELECT * FROM ers_user_roles; 
 SELECT * FROM ers_users; 
 SELECT * FROM ers_reimbursement; 
 
 
--  USER ROLE TABLE --
CREATE TABLE ERS_REIMBURSEMENT_STATUS (
     ERS_REIMBURSEMENT_STATUS_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     REIMB_STATUS VARCHAR(10) NOT NULL
 ); 

--  REIMBURSEMENT TYPE TABLE --
CREATE TABLE ERS_REIMBURSEMENT_TYPE (
     ERS_REIMBURSEMENT_TYPE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     REIMB_TYPE VARCHAR(10) NOT NULL
 );
 
 --  USER ROLES TABLE --
CREATE TABLE ERS_USER_ROLES  (
	ERS_USER_ROLES_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ROLE VARCHAR NOT NULL    
 );
 --  USERS TABLE --
 CREATE TABLE ERS_USERS (
     ERS_USERS_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     ERS_USERNAME VARCHAR(50) NOT NULL UNIQUE,
     ERS_PASSWORD VARCHAR(50) NOT NULL,
     USER_FIRST_NAME VARCHAR(100) NOT NULL,
     USER_LAST_NAME VARCHAR(100) NOT NULL,
     USER_EMAIL VARCHAR(150) NOT NULL UNIQUE,
     USER_ROLE_ID INTEGER NOT NULL,
     
     FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES (ERS_USER_ROLES_ID)
 );

-- REIMBURSEMENT --
CREATE TABLE ERS_REIMBURSEMENT (
     ERS_REIMBURSEMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     REIMBURSEMENT_AMOUNT INTEGER NOT NULL,
     REIMBURSEMENT_SUBMITTED TIMESTAMP NOT NULL,
     REIMBURSEMENT_RESOLVED TIMESTAMP NOT NULL,
     REIMBURSEMENT_DESCRIPTION VARCHAR(250) NOT NULL,
     REIMBURSEMENT_RECEIPT VARCHAR(250) NOT NULL,
     
     REIMBURSEMENT_AUTHOR INTEGER NOT NULL,
     REIMBURSEMENT_RESOLVER INTEGER NOT NULL,
     REIMBURSEMENT_STATUS_ID INTEGER NOT NULL,
     REIMBURSEMENT_TYPE_ID INTEGER NOT NULL,
     
     FOREIGN KEY (REIMBURSEMENT_AUTHOR) REFERENCES ERS_USERS (ERS_USERS_ID),
     FOREIGN KEY (REIMBURSEMENT_RESOLVER) REFERENCES ERS_USERS (ERS_USERS_ID),
     FOREIGN KEY (REIMBURSEMENT_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS (ERS_REIMBURSEMENT_STATUS_ID),
     FOREIGN KEY (REIMBURSEMENT_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE (ERS_REIMBURSEMENT_TYPE_ID)
 );
